### ISSUE TITLE
Remove Eloquent calls from views

### ISSUE THREAD

**Issue by laxsmi** [laxsmi/academico#111]
:warning: Shift detected Eloquent calls in the following views. You should keep *views* from interacting directly with your *models* by passing the necessary data from the *controller*.

- [ ] resources/views/reports/external.blade.php
- [ ] resources/views/reports/internal.blade.php

_Originally posted by @laxsmi in https://github.com/laxsmi/academico/pull/110#issuecomment-602048573_

**Comment by marcmarina** [comment]
Fixed it :D Will make a pull request.

**Comment by laxsmi** [comment]
#146
