### ISSUE TITLE
Fix incorrect media table name

### ISSUE THREAD

**Issue by laxsmi** [laxsmi/academico#163]

**Comment by damienBAUDET** [comment]
This issue should be solved with `composer update doctrine/inflector`
[https://github.com/vanilophp/framework/issues/72](url)

**Comment by laxsmi** [comment]
Thanks @damienBAUDET, I didn't notice a new release of doctrine/inflector had been released already. I merged your PR #164

**Comment by laxsmi** [comment]
@all-contributors please add @damienBAUDET for maintenance
