### ISSUE TITLE
always lowercase email addresses before saving to users table

### ISSUE THREAD

**Issue by laxsmi** [laxsmi/academico#166]

**Comment by mubarak23** [comment]
I will like to work on this issue.

**Comment by laxsmi** [comment]
Hi @mubarak23 and thank you for your interest in the project. You are welcome to submit a PR for this issue, and you will be credited as a contributor if your PR is accepted. Please let me know if you need any guidance or information to help you with the development process.

**Comment by mubarak23** [comment]
OK, I will go ahead and fork the repo and work on the issue thank you
